version: "3.6"
services:
  lms-app:
    image: app/lms:latest
    container_name: lms-app
    depends_on:
      - lms-db
    restart: always
    ports:
      - "8088:8000"
    networks:
      - lms
    environment:
      SERVER_PORT: 8088
  lms-db:
    image: postgres:15.3
    container_name: lms-db
    restart: always
    ports:
      - "5555:5432"
    networks:
      - lms
    environment:
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_str0ngp4ssr0d
      POSTGRES_DB: lms_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
networks:
  lms: